import React from 'react';

const Blog = () => {
    return (
        <div>
            <div class="flex justify-center items-center w-full  mx-auto gap-24 py-24">
               
                <div className='mx-10'>
                    <h1 class="text-4xl font-bold leading-20 mb-5">Featured products at one place</h1>
                    <p class="text-balance text-center text-[1rem] font-bold text-[#6C6C6C] mx-10">Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit quisquam adipisci deserunt commodi cumque ut molestias atque corporis accusamus recusandae minima cum unde assumenda possimus sapiente optio, quia modi quibusdam dolor. Sit natus maiores quasi officia dignissimos ex sed tenetur, consequatur et alias accusamus aliquid quo quas maxime a odio, est adipisci corrupti aliquam nesciunt nihil! Voluptas fugit sequi iste. Facilis modi ab voluptates non quaerat vero eaque laborum? Accusamus magnam vitae saepe odit doloremque alias fugit, dolor enim cumque, molestiae modi dolorem in similique ab minima iure animi dicta nam fugiat, atque non. Adipisci totam aspernatur sapiente sunt labore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente quidem eos veritatis magnam nemo accusantium ullam repudiandae velit minus, vero iusto architecto corporis quos possimus facilis vel ab iste fugit facere vitae, illum accusamus ut atque? Beatae dicta molestias nostrum recusandae debitis reiciendis harum maiores. Quas praesentium commodi eum quis quibusdam ad delectus expedita tenetur sed,<br />
                     asperiores laborum nulla sit, repellendus earum et rerum harum dolores labore nesciunt dolor sunt laboriosam aliquam unde! Hic autem consequatur necessitatibus commodi! Repudiandae aspernatur labore explicabo aliquam placeat officia doloremque, qui iure quos error maiores incidunt nemo soluta temporibus corporis ab, accusantium adipisci? Nemo eveniet omnis dicta inventore et nostrum, saepe odio exercitationem expedita incidunt at, reprehenderit architecto numquam atque delectus ullam, cumque error blanditiis enim necessitatibus dolore. Aliquam nemo inventore perferendis reprehenderit rem? Dignissimos reiciendis aspernatur doloribus neque accusamus placeat mollitia cupiditate cum et itaque? Sed quasi earum voluptates nesciunt non fugiat, dolore aspernatur fugit amet quidem possimus consectetur excepturi. Consequatur animi repudiandae omnis cupiditate deserunt. Temporibus asperiores error velit, rerum quibusdam maxime deserunt tempore, sint consectetur nihil quasi architecto laboriosam officia ducimus unde sapiente qui eligendi recusandae. Recusandae possimus minima saepe est sit illo architecto modi itaque neque, officia quidem veritatis eligendi quasi, alias aliquid aut id sed porro nihil sint. Asperiores voluptatem tenetur unde excepturi deserunt quam reiciendis ut magni. Perspiciatis tenetur animi, voluptates rem explicabo harum id. Aspernatur sequi officiis nemo delectus animi molestias hic. Eligendi quis dolor placeat ipsum neque, autem aut, fugiat incidunt rem rerum consectetur reiciendis quisquam excepturi ea nulla voluptate, quidem molestiae nobis voluptatum saepe magnam doloremque necessitatibus assumenda. Expedita labore quo a unde mollitia tempora beatae velit temporibus perferendis alias porro laborum, voluptates, doloremque placeat deserunt optio inventore molestiae non, iure laboriosam quae nobis. Laudantium tempora magni ullam! Possimus sequi debitis aspernatur delectus! Similique, nisi!</p>
                   
                </div>
            </div>
        </div>
    );
};

export default Blog;